require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'spec/fixtures/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'gemini_craft.gemspec'

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Exclude:
    - 'lib/gemini_craft.rb'

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# Disable line length check for gemspec
Layout/LineLength:
  Max: 120
  Exclude:
    - 'gemini_craft.gemspec'
    - 'spec/**/*'

# Disable development dependencies check in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Disable spec file path format checks
RSpec/FilePath:
  Exclude:
    - 'spec/gemini_craft.rb/**/*'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/gemini_craft.rb/**/*'

# Disable specific FactoryBot and Capybara cops that are causing errors
FactoryBot/CreateList:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false
  